name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Երբ push անես main branch-ին

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./   # Այստեղ պետք է root-ում լինի index.html ու մնացած ֆայլերը

      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v1
